---
- hosts: all
  become: yes
  vars:
    automation_user: "{{ automation_user }}"
    automation_group: "{{ automation_user }}"
    automation_home: "/home/{{ automation_user }}"
    rns_interface_device: "{{ rns_interface_device }}"
    rns_server_port: "{{ rns_server_port }}"
    rns_node_name: "{{ rns_node_name }}"
  roles:
    - security
    - rnsd